apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-submit.fullname" . }}
  labels:
    {{- include "spark-submit.labels" . | nindent 4 }}
data:
  spark-defaults.conf: |-
    spark.driver.host={{ .Values.driver.host }}
    spark.driver.port={{ .Values.driver.port }}