{{- $collectorService := include "spark-submit.fullname" .  -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spark-submit.fullname" . }}
  labels:
    {{ include "spark-submit.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}-test
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      restartPolicy: Never