apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-submit.fullname" . }}
  labels:
    {{ include "spark-submit.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "spark-submit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.driver.port }}
      targetPort: {{ .Values.driver.port }}
      name: spark-driver-port